["public NTP server"]
description = "öffentlicher NTP-Server"

["protocol version"]
description = "verwendete Version: `{used_version}`"
recommendations = [
  "verwenden Sie Version `{recommended_version}`"
]

["Mode 6"]
description = "erlaubt Mode-6-Anfragen (opcode {opcode}); Verstärkungsfaktor: {amplification_factor}"

["Mode 7"]
description = "erlaubt Mode-7-Anfragen (implementation {implementation}, req code {req_code}); Verstärkungsfaktor: {amplification_factor}"
references = [
  "[CVE-2013-5211](https://nvd.nist.gov/vuln/detail/CVE-2013-5211)"
]

["additional info"]
description = "zusätzliche Informationen: {info}"
